onCull = true
MaxEntityEntities = 128
qualityModes = "NORMAL"
RenderWeather = "CLOSE"
FastItemRender = true
RenderDisplayItem = true
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = true
startTime = 90.516
chatFix = true
onGui = true
GuiRXTX = false
GuiFPS = true
GuiCPU = false
GuiGPU = false
GuiRAM = true
GuiEntityCount = false
GuiPlayerPos = false
GuiServer = true
GuiCameraTarget = false
Mood = false
Particle = true
BlockBreakParticleMode = "NORMAL"
MaxParticleDistance = 128
WhiteListedParticle = []
BlackListedParticle = []
FPSMonitor = true
GuiEasyRamMode = true
GuiDisplayRamUsage = true
GuiX = 0
GuiY = 0
EntityRender = true
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = false
ParticleMaxAge = 1
GuiViewMode = "NULL"
EntityCullFov = 120
MinDistance = 5
EntityDistance = 64
TickPerformance = false
